
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gecibneiekktxkvoxsrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlY2libmVpZWtrdHhrdm94c3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTQ4NDEsImV4cCI6MjA2OTgzMDg0MX0.SAKb_xYZ4i3yuw47c6_RMurQg-GBqiN4HfEjFWjSYag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
